version: '3.8'
services:
  app:
    image: "surrealdb/surrealdb:latest"
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt